version: '3'
services:
  web:
    build: .
    command: python manage.py runserver --settings=property_admin.settings.local 0.0.0.0:8000 
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - migration
      - db
  migration:
    build: .
    command: python manage.py migrate --settings=property_admin.settings.local 
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"

volumes:
  postgres_data:
