# Generated by Django 3.1.7 on 2021-03-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('_deleted', models.BooleanField(default=False)),
                ('street', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Calle'), (1, 'Carrera'), (2, 'Avenida'), (3, 'Avenida Carrera'), (4, 'Avenida Calle'), (5, 'Circular'), (6, 'Circunvalar'), (7, 'Diagonal'), (8, 'Manzana'), (9, 'Transversal'), (10, 'Vía')], default=None, null=True)),
                ('street_number', models.CharField(blank=True, max_length=10, null=True)),
                ('corner', models.CharField(blank=True, max_length=10, null=True)),
                ('corner_number', models.IntegerField(blank=True, null=True)),
                ('rural', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección rural')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Urbano'), (2, 'Rural')], default=None, verbose_name='tipo de predio')),
                ('cadastral_id', models.CharField(max_length=50, unique=True, verbose_name='Cédula catastral')),
                ('registration_number', models.CharField(max_length=250, unique=True, verbose_name='Número de matrícula inmobiliaria')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
