# Generated by Django 3.1.7 on 2021-03-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20210324_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='corner_number',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(blank=True, choices=[('Calle', 'Calle'), ('Carrera', 'Carrera'), ('Avenida', 'Avenida'), ('Avenida Carrera', 'Avenida Carrera'), ('Avenida Calle', 'Avenida Calle'), ('Circular', 'Circular'), ('Circunvalar', 'Circunvalar'), ('Diagonal', 'Diagonal'), ('Manzana', 'Manzana'), ('Transversal', 'Transversal'), ('Vía', 'Vía')], default=None, max_length=20, null=True),
        ),
    ]
