# Generated by Django 3.1.7 on 2021-03-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20210324_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Urbano'), (2, 'Rural')], default=None, verbose_name='tipo de predio'),
        ),
    ]
